const mongoose = require('mongoose');

// Define the User Schema
const userSchema = new mongoose.Schema({
  googleId: {
    type: String,
    required: false
  },
  githubId: {
    type: String,
    required: false
  },
  name: {
    type: String,
    required: true
  },
  email: {
    type: String,
    required: true,
    unique: true
  },
  avatar: {
    type: String,
    required: false
  },
  provider: {
    type: String,  // Can be 'google', 'github', or 'local'
    required: true
  },
  password: {
    type: String,
    required: false  // Only required for local authentication
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  resume: { // Add this field to store the file path of the uploaded resume
    type: String,
    default: ''
  },
  resumeFeedback: { // Stores feedback generated by OpenAI or manually entered
    type: String,
    default: ''
  }
});

// Create a User model
const User = mongoose.model('User', userSchema);

module.exports = User;
